In [107]:
import numpy as np

def matrix_addition_1():
    '''
    This function returns addition of two matrix using manual creation of matrix
    '''
    m1 = [[1,2], [3,4]]
    m2 = [[5,6], [7,8]]
    result = [[0,0], [0,0]]
    for i in range(len(m1)):
        for j in range(len(m1[0])):
            result[i][j] = m1[i][j]+m2[i][j]
    return result

def matrix_addition_2():
    '''
    This function results addition of two matrix using numpy array creation of matrix
    '''
    m1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
    m2 = np.array([[3,2,1], [6,5,4], [9,8,7]])
    result = [[0,0,0],[0,0,0], [0,0,0]]
    for i in range(len(m1)):
        for j in range(len(m1[0])):
            result[i][j] = m1[i][j]+m2[i][j]
    return result
    
    
def matrix_addition_3():
    '''
    This function results addition of two matrix using numpy matrix creation
    '''
    m1 = np.matrix('5,6;7,8')
    m2 = np.matrix('3,4;5,6')
    result = np.matrix('0,0;0,0')
    for i in range(len(m1)):
        for j in range(len(m1[0])):
            result[i][j] = m1[i][j]+m2[i][j]
    return result


def matrix_addition_4():
    '''
    This function results addition of two matrix using numpy array and arange()
    '''
    m1 = np.array([np.arange(2,5), np.arange(4,7)])
    m2 = np.array([np.arange(6,9), np.arange(8,11)])
    result = [0,0,0], [0,0,0]
    for i in range(len(m1)):
        for j in range(len(m1[0])):
            result[i][j] = m1[i][j]+m2[i][j]
    return result

    
print('-----------------------')
print(matrix_addition_1())
print('-----------------------')
print(matrix_addition_2())
print('-----------------------')
print(matrix_addition_3())
print('-----------------------')
print(matrix_addition_4())
print('-----------------------')

-----------------------
[[6, 8], [10, 12]]
-----------------------
[[4, 4, 4], [10, 10, 10], [16, 16, 16]]
-----------------------
[[ 8 10]
 [12 14]]
-----------------------
([8, 10, 12], [12, 14, 16])
-----------------------


In [113]:
import numpy as np

def matrix_multiplication_1():
    '''
    This function returns multiplication of a matrix with a number
    '''
    A = 10
    B = [[6, 7],[8, 9]]
    return np.dot(A,B)
 


def matrix_multiplication_2():
    '''
    This function results multiplication of two matrix using numpy array dot()
    '''
    A = [[1,2,3], [4,5,6], [7,8,9]]
    B = [[6,7,8], [8,9,10], [2,3,4]]
    return np.dot(A,B)
    
    
def matrix_multiplication_3():
    '''
    This function results multiplication using numpy matmul()
    '''
    A = [[2, 4], [6, 8]]
    B = [[1, 3], [5, 7]]
 
    return np.matmul(A,B)   


def matrix_multiplication_4():
    '''
    This function results multiplication using numpy matmul()
    '''
    A = [[5, 0], [0, 5]]
    B = [5, 2]
 
    return np.matmul(A,B)


def matrix_multiplication_5():
    '''
    This function results multiplication using numpy matmul()
    '''
    A = np.arange(8).reshape(2, 2, 2)
    B = np.arange(4).reshape(2, 2)
 
    return np.matmul(A,B)


def matrix_multiplication_6():
    '''
    This function results multiplication using numpy multiply()
    '''
    A = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])
    B = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])

    return(np.multiply(A,B))


def matrix_multiplication_7():
    '''
    This function results multiplication using numpy matmul()
    '''
    A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
    B = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

    print(np.multiply(A[ 0,:], B[ 1,: ]))

    print("----------")

    print(np.multiply(A[ 1,:], B[ 0,:]))





print('-----------------------')
print(matrix_multiplication_1())
print('-----------------------')
print(matrix_multiplication_2())
print('-----------------------')
print(matrix_multiplication_3())
print('-----------------------')
print(matrix_multiplication_4())
print('-----------------------')
print(matrix_multiplication_5())
print('-----------------------')
print(matrix_multiplication_6())
print('-----------------------')
print(matrix_multiplication_7())
print('-----------------------')

-----------------------
[[60 70]
 [80 90]]
-----------------------
[[ 28  34  40]
 [ 76  91 106]
 [124 148 172]]
-----------------------
[[22 34]
 [46 74]]
-----------------------
[25 10]
-----------------------
[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]
-----------------------
[[ 1  6 15 28 45]
 [10 16 18 16 10]]
-----------------------
[ 16  34  54  76 100]
----------
[ 66  84 104 126 150]
None
-----------------------


In [121]:
def matrix_transpose():
    '''
    This function returns transpose of matrix
    '''
    mat = np.matrix('8,9;5,6')
    print(mat)
    print('----------')
    return mat.T

print(matrix_transpose())

[[8 9]
 [5 6]]
----------
[[8 5]
 [9 6]]


In [125]:
def alphabet_sort(words):
    '''
    This function returns list of sorted array in Alphabetical order
    '''
    result = sorted(words, key=str.lower)
    return result
alphabet_sort(['fjnfd', 'hdsbjds', 'chbbj', 'ajajcsn', 'cbdisvbids'])

['ajajcsn', 'cbdisvbids', 'chbbj', 'fjnfd', 'hdsbjds']

In [137]:
def string_punc(string):
    '''
    This function is to remove punctuation from string
    '''
    p = ['!','£','$','%','^','&','*','(',')','_']
    result = ''
    for i in string:
        if i not in p:
            result+=i
    return result

string = 'sah$%hcs$%^bc$%by!£$c$%bs£$%^uy'
print('Cleaned string is : ',string_punc(string))

Cleaned string is :  sahhcsbcbycbsuy
